### ISSUE TITLE
Is it possible to downgrade min PHP to PHP 5.6?

### ISSUE THREAD

**Issue by slaFFik** [wppunk/WPPlugin#12]
That’s the min version supported by WordPress.

As I understand, PHP 7.2 is used only because of tests libs, correct?

**Comment by wppunk** [comment]
Yep, it possible. You can change the PHP version into `composer.json`, `plugin-name.php`, `readme.txt`, `.phpcs.xml`.
Then replace `: void {` to `{` in the `src` folder and fix the type hinting for the `PluginName\Plugin::__construct` method.

But I don't want to implement these changes to the master branch because PHP7+ has a lof of strong stuff.

**Comment by slaFFik** [comment]
Yeah, I totally understand. 
Thanks for the answer, I will most likely proceed that way.
